apiVersion: batch/v1
kind: Job
metadata:
  name: bq-to-mongo-job
spec:
  template:
    spec:
      containers:
      - name: bq-to-mongo
        image: asia-south1-docker.pkg.dev/project-0eac7b4f-a7b9-40c4-8ac/my-repo/bq-to-mongo:latest

        env:
        - name: PROJECT_ID
          value: "project-0eac7b4f-a7b9-40c4-8ac"

        - name: DATASET
          value: "patients"

        - name: TABLE
          value: "dependants"

        - name: BATCH_SIZE
          value: "1000"

        # ✅ ADD THESE TWO (VERY IMPORTANT)
        - name: MONGO_DB
          value: "nilesh"

        - name: MONGO_COLLECTION
          value: "gketest"

        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: bq-mongo-secret
              key: MONGO_URI

      restartPolicy: Never
