apiVersion: v1
kind: Secret
metadata:
  name: bq-mongo-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://nileshkhabade:Hanumanji@08@cluster0.kei9ku3.mongodb.net/?appName=Cluster0"
  MONGO_DB: "nilesh"
  MONGO_COLLECTION: "gke"
